<h3>奎屯能耗分析模型</h3>
<table class="table table-bordered responsive table-striped table-sortable">
							<thead>
    							<tr>
    								<th class="header">序号</th>
    								<th class="header">指标名</th>
    								<th class="header">指标值</th>
    							</tr>
							</thead>
							<tbody>
														<tr>
								<td>1</td>
								<td><h4>中心局新楼7楼直流屏电源1#带载率</h4></td>
								<td><h4>40%</h4></td>
														</tr><tr>
								<td>2</td>
								<td><h4>中心局新楼7楼直流屏电源2#带载率</h4></td>
								<td><h4>56%</h4></td>
														</tr><tr>
								<td>3</td>
								<td><h4>中心局新楼7楼直流屏电源3#带载率</h4></td>
								<td><h4>87%</h4></td>
														</tr><tr>
								<td>4</td>
								<td><h4>中心局新楼7楼UPS电源1#带载率</h4></td>
								<td><h4>15%</h4></td>
														</tr><tr>
								<td>5</td>
								<td><h4>中心局新楼7楼UPS电源2#带载率</h4></td>
								<td><h4>21%</h4></td>
														</tr><tr>
								<td>6</td>
								<td><h4>中心局老楼1楼电力室直流屏电源1#带载率</h4></td>
								<td><h4>40%</h4></td>
														</tr><tr>
								<td>7</td>
								<td><h4>中心局老楼1楼电力室直流屏电源2#带载率</h4></td>
								<td><h4>50%</h4></td>
														</tr><tr>
								<td>8</td>
								<td><h4>低压总配电的带载率</h4></td>
								<td><h4>68%</h4></td>
														</tr><tr>
								<td>9</td>
								<td><h4>供电回路的带载率</h4></td>
								<td><h4>60%</h4></td>
														</tr><tr>
								<td>10</td>
								<td><h4>瞬时能效指标(PUE)</h4></td>
								<td><h4>1.68</h4></td>
														</tr><tr>
								<td>11</td>
								<td><h4>年度能效指标(PUE)</h4></td>
								<td><h4>1.76</h4></td>
														</tr></tbody>
							</table>
